### ISSUE TITLE
version 0.2.0 not published to hex

### ISSUE THREAD

**Issue by moalfa** [revelrylabs/ecto_soft_delete#13]
while the readme instructs to add `[{:ecto_soft_delete, "0.2.0"}]` to mix file. 
it seems like version 0.2.0 not published to hex yet https://hex.pm/packages/ecto_soft_delete.
a try to `mix deps.get` will throw the following error
`** (Mix) No matching version for ecto_soft_delete 0.2.0 (from: mix.exs) in registry The latest version is: 0.1.0`

**Comment by tonnenpinguin** [comment]
Also merging the updated dependency merge requests would be highly appreciated (otherwise this cannot be used with phoenix 1.4) :)

**Comment by bryanjos** [comment]
0.2.0 is now published. We still need to make an update to make sure it works with Ecto 3 fyi
