### ISSUE TITLE
Updating Dependencies

### ISSUE THREAD

**Issue by quinnmccourt** [revelrylabs/ecto_soft_delete#155]
Issue to track work on updating the dependencies on the project

**Comment by quinnmccourt** [comment]
Currently working on dependencies in this PR here: https://github.com/revelrylabs/ecto_soft_delete/pull/154/files

Required a bump to the elixir and erlang versions for some of the dependency bumps. After finding the right combo of elixir/erlang that travis and hex was happy with, we can build.

Current blocker is a test in ecto that is failing:

`  1) test soft_delete_columns adds deleted_at column (Ecto.SoftDelete.Migration.Test)
     test/soft_delete_migration_test.exs:15
     ** (FunctionClauseError) no function clause matching in Ecto.Migration.Runner.start_link/1

     The following arguments were given to Ecto.Migration.Runner.start_link/1:

         # 1
         {#PID<0.403.0>, Ecto.SoftDelete.Test.Repo, Ecto.SoftDelete.Migration.Test, :forward, :up, %{level: false, sql: false}}

     Attempted function clauses (showing 1 out of 1):

         def start_link({parent, repo, config, module, direction, migrator_direction, log})

     stacktrace:
       (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:42: Ecto.Migration.Runner.start_link/1
       test/soft_delete_migration_test.exs:10: Ecto.SoftDelete.Migration.Test.__ex_unit_setup_0/1
       test/soft_delete_migration_test.exs:1: Ecto.SoftDelete.Migration.Test.__ex_unit__/2`
       
       It looks like it's missing an argument in the config, but I need to put my pencil down here for this week.

**Comment by Samkeer1** [comment]
Here's what allowed me to install this version of erlang: https://github.com/erlang/otp/issues/7687#issuecomment-1737184968

`KERL_CONFIGURE_OPTIONS="--disable-jit" asdf install erlang 25.3`

**Comment by stuartjohnpage** [comment]
I'm closing this - we've updated all the deps we can for now.
