### ISSUE TITLE
The deactivated_at clause inclusion check

### ISSUE THREAD

**Issue by ayan-haider** [revelrylabs/ecto_soft_delete#159]
The `deleted_at` clause [here](https://github.com/revelrylabs/ecto_soft_delete/blob/a0934f9c7c1d538512e2f01f9874e2334c7e20ff/lib/ecto/soft_delete_repo.ex#L94) works perfectly fine when we apply each filter in separate `where` expressions. 
However, if we do something like this: 
```
from(c in City, where: c.country == "Sweden" and is_nil(c.deleted_at))
```
The code does not recognize it and adds another check that is exactly the same.

**Comment by quinnmccourt** [comment]
Thank you for your contribution! I've given feedback on your PR, but I believe this would be a good addition.
